### ISSUE TITLE
BlackHarmony - zajętość Flasha

### ISSUE THREAD

**Issue by areqq** [j00zek/eePlugins#3]
cześć

Na moim VU+ zero ciągle mam problem z miejscem ;(
Instaluje i updatuje opkg z repo

BlackHarmony piękne jest, ale zajmuje coraz więcej:

```
# du -sh /usr/share/enigma2/BlackHarmony
55.2M	/usr/share/enigma2/BlackHarmony

22.4M	/usr/share/enigma2/BlackHarmony/allBars
```
Może by się dało znacznie odchudzić paczkę ? Może jakoś podzielić na kilka mniejszych ?
Główny winowajca to folder allBars

**Comment by j00zek** [comment]
to nie takie proste, zrobienie oddzielnych paczek wymaga zmian w userskin, żeby nikt się nie pogubił

**Comment by areqq** [comment]
pewnie userskin musiał by pobierać "warianty" z netu i instalować tylko te wybrane - domyślam się, że to nie trywialne
to może chociaż na początek paczka BlackHarmony-minimal bez możliwości wyboru różnych Barów itp ?

**Comment by j00zek** [comment]
a nie możesz sobie zmapować tego katalogu na penie?

**Comment by areqq** [comment]
tak, zrobiłem sobie link doraźnie, ale pomyślałem ze nie tylko ja mogę mieć ten problem i może warto to jakoś rozwiązać, bo pewnie dodatków będzie przybywać. O ile na nowym ARM Flashe są olbrzymie to na starszych mipsel robi się ciasno.

**Comment by j00zek** [comment]
coś pomyślę

**Comment by j00zek** [comment]
coś tam zmieniłem, mam nadzieję, że Ci teraz się zmieści

**Comment by areqq** [comment]
dzięki !
znacznie mniej teraz zajmuje:
37.3M	/usr/share/enigma2/BlackHarmony
6.7M	/usr/share/enigma2/BlackHarmony/allBars/

**Comment by areqq** [comment]
może jeszcze warto zaoptymalizować obrazki ?
Proste przepuszczenie png przez pngquant
find . -name '*.png' -exec pngquant --speed 1 --ext .png --force 256 {} \;

zmniejszyło całość o kolejne 9MB

**Comment by j00zek** [comment]
nie można, bo traci się na jakości.

**Comment by areqq** [comment]
a mógłbyś podzielić paczkę na dwie ? 
BlackHarmony-base - zawierający minimum niezbędne do działania bez możliwość customizacji
BlackHarmony - zawierający całą resztę z obecnej paczki i wymagającej BlackHarmony-base 

Minimaliści mogli by instalować tylko BlackHarmony-base, a dla całej reszty by się nic nie zmieniło
