### ISSUE TITLE
j00zekE2iPlayer.py :RemindedMinutes should show only minutes, not seconds.

### ISSUE THREAD

**Issue by willy014** [j00zek/eePlugins#8]
RemindedMinutes should show only minutes, not seconds in j00zekE2iPlayer.py 
How to release it ?

**Comment by j00zek** [comment]
Thanks for raising this. Should be correct now.

**Comment by willy014** [comment]
thx for your work,
but now it shows "0:68"
but for small display simple  "68" ist better way.
